[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "muffin include isolate umbrella elder whip rubber design license three injury hurdle cluster crew sentence suggest beef normal vessel convince climb all sibling jewel"
